enum EffectId {
    Test,
    PoisonSpiritSnake,
    WolfsBane,
    Sage,
    Fox,
    Yerba,
    Rage,
    Bless,
    Agave,
    FireAntInfected,
    FireAntInfectionStep,
    FireAntQueenHarden,
    FireAntQueenPheromone,
    Tequila,
    Prayer,
    Dodge,
    MagicShieldRed,
    MagicShieldGrey,
    MagicShieldGold,
    BackstabDodge,
    Rush,
    TreantRage,
    TreantRageTrigger,
    BottleFairy,
    WillOWispDodge,
    Regeneration,
    Unhittable,
}

export default EffectId;