enum CreatureId{
    PlayerCharacter,
    Goblin,
    GoblinRaidingParty,
    GoblinSoldier,
    GoblinSneak,
    GoblinChief,
    FireAntMite,
    FireAntWorker,
    FireAntSoldier,
    FireAntInfected,
    FireAntQueen,
    GhostGuardian,
    GhostHound,
    GiantToad,
    GiantRat,
    ExiledMagician,
    WillOWisp,
    Treant,
    Faun,
    Werewolf,
    OldWillow,
    CorruptedFairies,
    Pixie,
    GiantFly,
    GiantWasp,
    PetAnteater,
}

export default CreatureId;