enum ItemId {
    BareHands,
    HandAxe,
    WoodShield,
    HuntingSword,
    WornLeathers,
    TabletOfHealing,
    SonicLongsword,
    Vial,
    TableOfPoison,
    GoblinRaidingPartyWeapon,
    GoblinSneakPoisonWeapon,
    ScarabToken,
    Agave,
    Acai,
    Bane,
    Sage,
    Fox,
    Yerba,
    Mezcal,
    StoneAxe,
    StoneDagger,
    AlphaKey,
    Tent,
    NorthernSteppesMapPiece,
    RingOfFortune,
    WornLeatherHelmet,
    RingOfHealth,
    RingOfStrength,
    RingOfAgility,
    Dagger,    
    TabletOfFire,
}

export default ItemId;