enum ItemId {
    BareHands,
    HandAxe,
    WoodShield,
    HuntingSword,
    WornLeathers,
    TabletOfHealing,
    SonicLongsword,
    Vial,
    TableOfPoison,
    GoblinRaidingPartyWeapon,
    GoblinSneakPoisonWeapon,
    ScarabToken,
    Agave,
    Acai,
    Bane,
    Sage,
    Fox,
    Yerba,
    Mezcal,
    StoneAxe,
    StoneDagger,
    BetaKey,
}

export default ItemId;